/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dbapp;

import org.junit.jupiter.api.Test;

import dbapp.model.ProductRepository;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
    }
}
